version: '3'
services:
  sambot_db:
    restart: always
    image: mariadb:10.6.4
    networks: 
      - sambot_default
    ports:
      - "5555:3306"
    volumes:
      - sambot_db:/var/lib/mysql
    env_file:
      - ../.env

volumes:
  sambot_db:
    external: true

networks:
  sambot_default:
    external: true